"""
    Apache NiFi REST API

    REST API definition for Apache NiFi web services

    OpenAPI spec version: 2.5.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
import re


class ControllerBulletinsEntity(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bulletins': 'list[BulletinEntity]',
'controller_service_bulletins': 'list[BulletinEntity]',
'flow_analysis_rule_bulletins': 'list[BulletinEntity]',
'flow_registry_client_bulletins': 'list[BulletinEntity]',
'parameter_provider_bulletins': 'list[BulletinEntity]',
'reporting_task_bulletins': 'list[BulletinEntity]'    }

    attribute_map = {
        'bulletins': 'bulletins',
'controller_service_bulletins': 'controllerServiceBulletins',
'flow_analysis_rule_bulletins': 'flowAnalysisRuleBulletins',
'flow_registry_client_bulletins': 'flowRegistryClientBulletins',
'parameter_provider_bulletins': 'parameterProviderBulletins',
'reporting_task_bulletins': 'reportingTaskBulletins'    }

    def __init__(self, bulletins=None, controller_service_bulletins=None, flow_analysis_rule_bulletins=None, flow_registry_client_bulletins=None, parameter_provider_bulletins=None, reporting_task_bulletins=None):
        """
        ControllerBulletinsEntity - a model defined in Swagger
        """

        self._bulletins = None
        self._controller_service_bulletins = None
        self._flow_analysis_rule_bulletins = None
        self._flow_registry_client_bulletins = None
        self._parameter_provider_bulletins = None
        self._reporting_task_bulletins = None

        if bulletins is not None:
          self.bulletins = bulletins
        if controller_service_bulletins is not None:
          self.controller_service_bulletins = controller_service_bulletins
        if flow_analysis_rule_bulletins is not None:
          self.flow_analysis_rule_bulletins = flow_analysis_rule_bulletins
        if flow_registry_client_bulletins is not None:
          self.flow_registry_client_bulletins = flow_registry_client_bulletins
        if parameter_provider_bulletins is not None:
          self.parameter_provider_bulletins = parameter_provider_bulletins
        if reporting_task_bulletins is not None:
          self.reporting_task_bulletins = reporting_task_bulletins

    @property
    def bulletins(self):
        """
        Gets the bulletins of this ControllerBulletinsEntity.
        System level bulletins to be reported to the user.

        :return: The bulletins of this ControllerBulletinsEntity.
        :rtype: list[BulletinEntity]
        """
        return self._bulletins

    @bulletins.setter
    def bulletins(self, bulletins):
        """
        Sets the bulletins of this ControllerBulletinsEntity.
        System level bulletins to be reported to the user.

        :param bulletins: The bulletins of this ControllerBulletinsEntity.
        :type: list[BulletinEntity]
        """

        self._bulletins = bulletins

    @property
    def controller_service_bulletins(self):
        """
        Gets the controller_service_bulletins of this ControllerBulletinsEntity.
        Controller service bulletins to be reported to the user.

        :return: The controller_service_bulletins of this ControllerBulletinsEntity.
        :rtype: list[BulletinEntity]
        """
        return self._controller_service_bulletins

    @controller_service_bulletins.setter
    def controller_service_bulletins(self, controller_service_bulletins):
        """
        Sets the controller_service_bulletins of this ControllerBulletinsEntity.
        Controller service bulletins to be reported to the user.

        :param controller_service_bulletins: The controller_service_bulletins of this ControllerBulletinsEntity.
        :type: list[BulletinEntity]
        """

        self._controller_service_bulletins = controller_service_bulletins

    @property
    def flow_analysis_rule_bulletins(self):
        """
        Gets the flow_analysis_rule_bulletins of this ControllerBulletinsEntity.
        Flow Analysis Rule bulletins to be reported to the user.

        :return: The flow_analysis_rule_bulletins of this ControllerBulletinsEntity.
        :rtype: list[BulletinEntity]
        """
        return self._flow_analysis_rule_bulletins

    @flow_analysis_rule_bulletins.setter
    def flow_analysis_rule_bulletins(self, flow_analysis_rule_bulletins):
        """
        Sets the flow_analysis_rule_bulletins of this ControllerBulletinsEntity.
        Flow Analysis Rule bulletins to be reported to the user.

        :param flow_analysis_rule_bulletins: The flow_analysis_rule_bulletins of this ControllerBulletinsEntity.
        :type: list[BulletinEntity]
        """

        self._flow_analysis_rule_bulletins = flow_analysis_rule_bulletins

    @property
    def flow_registry_client_bulletins(self):
        """
        Gets the flow_registry_client_bulletins of this ControllerBulletinsEntity.
        Flow registry client bulletins to be reported to the user.

        :return: The flow_registry_client_bulletins of this ControllerBulletinsEntity.
        :rtype: list[BulletinEntity]
        """
        return self._flow_registry_client_bulletins

    @flow_registry_client_bulletins.setter
    def flow_registry_client_bulletins(self, flow_registry_client_bulletins):
        """
        Sets the flow_registry_client_bulletins of this ControllerBulletinsEntity.
        Flow registry client bulletins to be reported to the user.

        :param flow_registry_client_bulletins: The flow_registry_client_bulletins of this ControllerBulletinsEntity.
        :type: list[BulletinEntity]
        """

        self._flow_registry_client_bulletins = flow_registry_client_bulletins

    @property
    def parameter_provider_bulletins(self):
        """
        Gets the parameter_provider_bulletins of this ControllerBulletinsEntity.
        Parameter provider bulletins to be reported to the user.

        :return: The parameter_provider_bulletins of this ControllerBulletinsEntity.
        :rtype: list[BulletinEntity]
        """
        return self._parameter_provider_bulletins

    @parameter_provider_bulletins.setter
    def parameter_provider_bulletins(self, parameter_provider_bulletins):
        """
        Sets the parameter_provider_bulletins of this ControllerBulletinsEntity.
        Parameter provider bulletins to be reported to the user.

        :param parameter_provider_bulletins: The parameter_provider_bulletins of this ControllerBulletinsEntity.
        :type: list[BulletinEntity]
        """

        self._parameter_provider_bulletins = parameter_provider_bulletins

    @property
    def reporting_task_bulletins(self):
        """
        Gets the reporting_task_bulletins of this ControllerBulletinsEntity.
        Reporting task bulletins to be reported to the user.

        :return: The reporting_task_bulletins of this ControllerBulletinsEntity.
        :rtype: list[BulletinEntity]
        """
        return self._reporting_task_bulletins

    @reporting_task_bulletins.setter
    def reporting_task_bulletins(self, reporting_task_bulletins):
        """
        Sets the reporting_task_bulletins of this ControllerBulletinsEntity.
        Reporting task bulletins to be reported to the user.

        :param reporting_task_bulletins: The reporting_task_bulletins of this ControllerBulletinsEntity.
        :type: list[BulletinEntity]
        """

        self._reporting_task_bulletins = reporting_task_bulletins

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ControllerBulletinsEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
