"""
    Apache NiFi REST API

    REST API definition for Apache NiFi web services

    OpenAPI spec version: 2.10.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
import re


class CreateFlowBranchRequestEntity(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'branch': 'str',
'disconnected_node_acknowledged': 'bool',
'process_group_revision': 'RevisionDTO',
'source_branch': 'str',
'source_version': 'str'    }

    attribute_map = {
        'branch': 'branch',
'disconnected_node_acknowledged': 'disconnectedNodeAcknowledged',
'process_group_revision': 'processGroupRevision',
'source_branch': 'sourceBranch',
'source_version': 'sourceVersion'    }

    def __init__(self, branch=None, disconnected_node_acknowledged=None, process_group_revision=None, source_branch=None, source_version=None):
        """
        CreateFlowBranchRequestEntity - a model defined in Swagger
        """

        self._branch = None
        self._disconnected_node_acknowledged = None
        self._process_group_revision = None
        self._source_branch = None
        self._source_version = None

        if branch is not None:
          self.branch = branch
        if disconnected_node_acknowledged is not None:
          self.disconnected_node_acknowledged = disconnected_node_acknowledged
        if process_group_revision is not None:
          self.process_group_revision = process_group_revision
        if source_branch is not None:
          self.source_branch = source_branch
        if source_version is not None:
          self.source_version = source_version

    @property
    def branch(self):
        """
        Gets the branch of this CreateFlowBranchRequestEntity.
        The name of the new branch to create

        :return: The branch of this CreateFlowBranchRequestEntity.
        :rtype: str
        """
        return self._branch

    @branch.setter
    def branch(self, branch):
        """
        Sets the branch of this CreateFlowBranchRequestEntity.
        The name of the new branch to create

        :param branch: The branch of this CreateFlowBranchRequestEntity.
        :type: str
        """

        self._branch = branch

    @property
    def disconnected_node_acknowledged(self):
        """
        Gets the disconnected_node_acknowledged of this CreateFlowBranchRequestEntity.
        Acknowledges that this node is disconnected to allow for mutable requests to proceed.

        :return: The disconnected_node_acknowledged of this CreateFlowBranchRequestEntity.
        :rtype: bool
        """
        return self._disconnected_node_acknowledged

    @disconnected_node_acknowledged.setter
    def disconnected_node_acknowledged(self, disconnected_node_acknowledged):
        """
        Sets the disconnected_node_acknowledged of this CreateFlowBranchRequestEntity.
        Acknowledges that this node is disconnected to allow for mutable requests to proceed.

        :param disconnected_node_acknowledged: The disconnected_node_acknowledged of this CreateFlowBranchRequestEntity.
        :type: bool
        """

        self._disconnected_node_acknowledged = disconnected_node_acknowledged

    @property
    def process_group_revision(self):
        """
        Gets the process_group_revision of this CreateFlowBranchRequestEntity.

        :return: The process_group_revision of this CreateFlowBranchRequestEntity.
        :rtype: RevisionDTO
        """
        return self._process_group_revision

    @process_group_revision.setter
    def process_group_revision(self, process_group_revision):
        """
        Sets the process_group_revision of this CreateFlowBranchRequestEntity.

        :param process_group_revision: The process_group_revision of this CreateFlowBranchRequestEntity.
        :type: RevisionDTO
        """

        self._process_group_revision = process_group_revision

    @property
    def source_branch(self):
        """
        Gets the source_branch of this CreateFlowBranchRequestEntity.
        The name of the source branch to create the new branch from. Defaults to the branch currently tracking in NiFi.

        :return: The source_branch of this CreateFlowBranchRequestEntity.
        :rtype: str
        """
        return self._source_branch

    @source_branch.setter
    def source_branch(self, source_branch):
        """
        Sets the source_branch of this CreateFlowBranchRequestEntity.
        The name of the source branch to create the new branch from. Defaults to the branch currently tracking in NiFi.

        :param source_branch: The source_branch of this CreateFlowBranchRequestEntity.
        :type: str
        """

        self._source_branch = source_branch

    @property
    def source_version(self):
        """
        Gets the source_version of this CreateFlowBranchRequestEntity.
        The version on the source branch to use when creating the new branch. Defaults to the version currently tracked by NiFi.

        :return: The source_version of this CreateFlowBranchRequestEntity.
        :rtype: str
        """
        return self._source_version

    @source_version.setter
    def source_version(self, source_version):
        """
        Sets the source_version of this CreateFlowBranchRequestEntity.
        The version on the source branch to use when creating the new branch. Defaults to the version currently tracked by NiFi.

        :param source_version: The source_version of this CreateFlowBranchRequestEntity.
        :type: str
        """

        self._source_version = source_version

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in self.swagger_types.items():
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CreateFlowBranchRequestEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
